ORG #C000
read"initialisation_du_jeu_ROM.asm"
read"monstre1_ROM.asm"
read"monstre2_ROM.asm"
read"monstre3_ROM.asm"
read"monstre4_ROM.asm"
read"monstre5_ROM.asm"
read"monstre6_ROM.asm"
read"monstre7_ROM.asm"
read"boss_donjon_3_ROM.asm"
read"boss_donjon_4_ROM.asm"
read"boule_de_feu_ROM.asm"
read"gestion_objets_hyrule_ROM.asm"
read"poisson_zora_ROM.asm"
read"bombe_ROM.asm"
read"feu_ROM.asm"
read"fleche_ROM.asm"
read"hud_ROM.asm"
read"fire2_init_ROM_suite.asm"
read"fire1_init_ROM.asm"
read"affiche_passage_zelda.asm"
read"collision_ROM8.asm"
read"fin_du_jeu_ROM.asm"
read"champi_rouge_vert_pourrit.asm"
read"table_init_monstres_ROM8.asm"
read"collisions_decors_ROM8.asm"
read"collision_suite_ROM8.asm"
read"boss_donjon_1_ROM8.asm"
read"boss_donjon_2_ROM8.asm"
read"echelle_ROM8.asm"

read"gameover_ROM.asm"


