; Zelda, AKG format, v1.0.

; Generated by Arkos Tracker 2.

Start
StartDisarkGenerateExternalLabel

DisarkByteRegionStart0
	db "AT20"
DisarkPointerRegionStart1
	dw ArpeggioTable	; The address of the Arpeggio table.
	dw PitchTable	; The address of the Pitch table.
	dw InstrumentTable	; The address of the Instrument table.
	dw EffectBlockTable	; The address of the Effect Block table.
DisarkPointerRegionEnd1


; The addresses of each Subsong:
DisarkPointerRegionStart2
	dw Subsong0_Start
	dw Subsong1_Start
	dw Subsong2_Start
	dw Subsong3_Start
	dw Subsong4_Start
	dw Subsong5_Start
	dw Subsong6_Start
	dw Subsong7_Start
DisarkPointerRegionEnd2

; Declares all the Arpeggios.
ArpeggioTable
DisarkPointerRegionStart3
	dw Arpeggio1
DisarkPointerRegionEnd3

Arpeggio1
	db 1	; The speed.

	db 0
	db 12
	db 0
	db -128
DisarkWordForceReference4
	dw Arpeggio1 + 0 + 1	; Loop.

; Declares all the Pitches.
PitchTable
DisarkPointerRegionStart5
DisarkPointerRegionEnd5

; Declares all the Instruments.
InstrumentTable
DisarkPointerRegionStart6
	dw EmptyInstrument
	dw Instrument1
DisarkPointerRegionEnd6

EmptyInstrument
	db 0	; The speed (>0, 0 for 256).
EmptyInstrument_Loop	db 0	; No Soft no Hard. Volume: 0. Noise? false.

	db 6	; Loop to silence.

Instrument1
	db 5	; The speed (>0, 0 for 256).
	db 249	; Soft only. Volume: 15. Volume only.

	db 241	; Soft only. Volume: 14. Volume only.

	db 233	; Soft only. Volume: 13. Volume only.

	db 225	; Soft only. Volume: 12. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 201	; Soft only. Volume: 9. Volume only.

	db 193	; Soft only. Volume: 8. Volume only.

	db 185	; Soft only. Volume: 7. Volume only.

	db 177	; Soft only. Volume: 6. Volume only.

	db 169	; Soft only. Volume: 5. Volume only.

	db 161	; Soft only. Volume: 4. Volume only.

	db 153	; Soft only. Volume: 3. Volume only.

	db 145	; Soft only. Volume: 2. Volume only.

	db 137	; Soft only. Volume: 1. Volume only.

	db 6	; Loop to silence.


; The indexes of the effect blocks used by this song.
EffectBlockTable
DisarkPointerRegionStart7
	dw EffectBlock_P4P6	; Index 0
	dw EffectBlock_P4P4	; Index 1
	dw EffectBlock_P5P6P6P0	; Index 2
DisarkPointerRegionEnd7

EffectBlock_P4P4
	db 4, 4
EffectBlock_P4P6
	db 4, 6
EffectBlock_P5P6P6P0
	db 5, 6, 6, 0

DisarkByteRegionEnd0

; Subsong 0
; ----------------------
Subsong0_DisarkByteRegionStart0
Subsong0_Start
	db 2	; ReplayFrequency (0=12.5hz, 1=25, 2=50, 3=100, 4=150, 5=300).
	db 0	; Digichannel (0-2).
	db 1	; PSG count (>0).
	db 0	; Loop start index (>=0).
	db 14	; End index (>=0).
	db 6	; Initial speed (>=0).
	db 17	; Base note index (>=0).

Subsong0_Linker
Subsong0_DisarkPointerRegionStart1
; Position 0
Subsong0_Linker_Loop
	dw Subsong0_Track0
	dw Subsong0_Track1
	dw Subsong0_Track2
	dw Subsong0_LinkerBlock0

; Position 1
	dw Subsong0_Track3
	dw Subsong0_Track4
	dw Subsong0_Track5
	dw Subsong0_LinkerBlock1

; Position 2
	dw Subsong0_Track6
	dw Subsong0_Track7
	dw Subsong0_Track8
	dw Subsong0_LinkerBlock1

; Position 3
	dw Subsong0_Track9
	dw Subsong0_Track10
	dw Subsong0_Track11
	dw Subsong0_LinkerBlock1

; Position 4
	dw Subsong0_Track9
	dw Subsong0_Track12
	dw Subsong0_Track13
	dw Subsong0_LinkerBlock1

; Position 5
	dw Subsong0_Track14
	dw Subsong0_Track15
	dw Subsong0_Track11
	dw Subsong0_LinkerBlock1

; Position 6
	dw Subsong0_Track16
	dw Subsong0_Track17
	dw Subsong0_Track18
	dw Subsong0_LinkerBlock1

; Position 7
	dw Subsong0_Track19
	dw Subsong0_Track20
	dw Subsong0_Track21
	dw Subsong0_LinkerBlock1

; Position 8
	dw Subsong0_Track22
	dw Subsong0_Track23
	dw Subsong0_Track24
	dw Subsong0_LinkerBlock1

; Position 9
	dw Subsong0_Track14
	dw Subsong0_Track15
	dw Subsong0_Track11
	dw Subsong0_LinkerBlock1

; Position 10
	dw Subsong0_Track25
	dw Subsong0_Track26
	dw Subsong0_Track13
	dw Subsong0_LinkerBlock1

; Position 11
	dw Subsong0_Track27
	dw Subsong0_Track28
	dw Subsong0_Track29
	dw Subsong0_LinkerBlock1

; Position 12
	dw Subsong0_Track30
	dw Subsong0_Track28
	dw Subsong0_Track29
	dw Subsong0_LinkerBlock1

; Position 13
	dw Subsong0_Track31
	dw Subsong0_Track32
	dw Subsong0_Track21
	dw Subsong0_LinkerBlock1

; Position 14
	dw Subsong0_Track22
	dw Subsong0_Track23
	dw Subsong0_Track24
	dw Subsong0_LinkerBlock1

Subsong0_DisarkPointerRegionEnd1
	dw 0	; Loop.
Subsong0_DisarkWordForceReference2
	dw Subsong0_Linker_Loop

Subsong0_LinkerBlock0
	db 64	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
Subsong0_DisarkWordForceReference3
	dw Subsong0_SpeedTrack0	; SpeedTrack address.
Subsong0_DisarkWordForceReference4
	dw Subsong0_EventTrack0	; EventTrack address.
Subsong0_LinkerBlock1
	db 64	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
Subsong0_DisarkWordForceReference5
	dw Subsong0_SpeedTrack1	; SpeedTrack address.
Subsong0_DisarkWordForceReference6
	dw Subsong0_EventTrack0	; EventTrack address.

Subsong0_Track0
	db 221
	db 1	; New Instrument (1).
	db 0	; Index to an effect block.
	db 61, 18	; Waits for 19 lines.

	db 24
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 24
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 29
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 27
	db 60	; Waits for 1 line.

	db 25
	db 60	; Waits for 1 line.

	db 27
	db 61, 127	; Waits for 128 lines.


Subsong0_Track1
	db 245
	db 1	; New Instrument (1).
	db 2	; Index to an effect block.
	db 61, 18	; Waits for 19 lines.

	db 48
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 48
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 53
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 51
	db 60	; Waits for 1 line.

	db 49
	db 60	; Waits for 1 line.

	db 51
	db 61, 127	; Waits for 128 lines.


Subsong0_Track2
	db 197
	db 1	; New Instrument (1).
	db 0	; Index to an effect block.
	db 61, 6	; Waits for 7 lines.

	db 12
	db 61, 6	; Waits for 7 lines.

	db 17
	db 61, 14	; Waits for 15 lines.

	db 3
	db 61, 6	; Waits for 7 lines.

	db 10
	db 61, 6	; Waits for 7 lines.

	db 15
	db 61, 127	; Waits for 128 lines.


Subsong0_Track3
	db 157
	db 1	; New Instrument (1).
	db 61, 18	; Waits for 19 lines.

	db 25
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 25
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 29
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 28
	db 60	; Waits for 1 line.

	db 26
	db 60	; Waits for 1 line.

	db 28
	db 61, 127	; Waits for 128 lines.


Subsong0_Track4
	db 181
	db 1	; New Instrument (1).
	db 61, 18	; Waits for 19 lines.

	db 49
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 49
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 53
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 52
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 52
	db 61, 127	; Waits for 128 lines.


Subsong0_Track5
	db 141
	db 1	; New Instrument (1).
	db 61, 6	; Waits for 7 lines.

	db 20
	db 61, 6	; Waits for 7 lines.

	db 25
	db 61, 14	; Waits for 15 lines.

	db 12
	db 61, 6	; Waits for 7 lines.

	db 19
	db 61, 6	; Waits for 7 lines.

	db 24
	db 61, 127	; Waits for 128 lines.


Subsong0_Track6
	db 136
	db 1	; New Instrument (1).
	db 61, 30	; Waits for 31 lines.

	db 8
	db 61, 127	; Waits for 128 lines.


Subsong0_Track7
	db 164
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 36
	db 60	; Waits for 1 line.

	db 29
	db 60	; Waits for 1 line.

	db 36
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 36
	db 60	; Waits for 1 line.

	db 29
	db 60	; Waits for 1 line.

	db 36
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 36
	db 60	; Waits for 1 line.

	db 29
	db 60	; Waits for 1 line.

	db 36
	db 60	; Waits for 1 line.

	db 29
	db 60	; Waits for 1 line.

	db 36
	db 60	; Waits for 1 line.

	db 29
	db 60	; Waits for 1 line.

	db 36
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 36
	db 60	; Waits for 1 line.

	db 29
	db 60	; Waits for 1 line.

	db 36
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 36
	db 60	; Waits for 1 line.

	db 29
	db 60	; Waits for 1 line.

	db 36
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 36
	db 60	; Waits for 1 line.

	db 29
	db 60	; Waits for 1 line.

	db 36
	db 60	; Waits for 1 line.

	db 29
	db 60	; Waits for 1 line.

	db 36
	db 60	; Waits for 1 line.

	db 29
	db 61, 127	; Waits for 128 lines.


Subsong0_Track8
	db 145
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 17
	db 60	; Waits for 1 line.

	db 17
	db 60	; Waits for 1 line.

	db 17
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 17
	db 60	; Waits for 1 line.

	db 17
	db 60	; Waits for 1 line.

	db 17
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 17
	db 60	; Waits for 1 line.

	db 17
	db 60	; Waits for 1 line.

	db 17
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 17
	db 60	; Waits for 1 line.

	db 17
	db 60	; Waits for 1 line.

	db 17
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 17
	db 60	; Waits for 1 line.

	db 17
	db 60	; Waits for 1 line.

	db 17
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 17
	db 60	; Waits for 1 line.

	db 17
	db 60	; Waits for 1 line.

	db 17
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 17
	db 60	; Waits for 1 line.

	db 17
	db 60	; Waits for 1 line.

	db 17
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 17
	db 60	; Waits for 1 line.

	db 17
	db 61, 127	; Waits for 128 lines.


Subsong0_Track9
	db 169
	db 1	; New Instrument (1).
	db 61, 6	; Waits for 7 lines.

	db 36
	db 61, 10	; Waits for 11 lines.

	db 41
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 41
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 46
	db 60	; Waits for 1 line.

	db 48
	db 61, 127	; Waits for 128 lines.


Subsong0_Track10
	db 164
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 36
	db 60	; Waits for 1 line.

	db 29
	db 60	; Waits for 1 line.

	db 36
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 36
	db 60	; Waits for 1 line.

	db 29
	db 60	; Waits for 1 line.

	db 36
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 36
	db 60	; Waits for 1 line.

	db 29
	db 60	; Waits for 1 line.

	db 36
	db 60	; Waits for 1 line.

	db 29
	db 60	; Waits for 1 line.

	db 36
	db 60	; Waits for 1 line.

	db 29
	db 60	; Waits for 1 line.

	db 34
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 41
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 41
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 46
	db 60	; Waits for 1 line.

	db 48
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 34
	db 60	; Waits for 1 line.

	db 27
	db 60	; Waits for 1 line.

	db 34
	db 60	; Waits for 1 line.

	db 27
	db 60	; Waits for 1 line.

	db 34
	db 60	; Waits for 1 line.

	db 27
	db 61, 127	; Waits for 128 lines.


Subsong0_Track11
	db 133
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 5
	db 60	; Waits for 1 line.

	db 5
	db 60	; Waits for 1 line.

	db 5
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 5
	db 60	; Waits for 1 line.

	db 5
	db 60	; Waits for 1 line.

	db 5
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 5
	db 60	; Waits for 1 line.

	db 5
	db 60	; Waits for 1 line.

	db 5
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 5
	db 60	; Waits for 1 line.

	db 5
	db 60	; Waits for 1 line.

	db 3
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 3
	db 60	; Waits for 1 line.

	db 3
	db 60	; Waits for 1 line.

	db 3
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 3
	db 60	; Waits for 1 line.

	db 3
	db 60	; Waits for 1 line.

	db 3
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 3
	db 60	; Waits for 1 line.

	db 3
	db 60	; Waits for 1 line.

	db 3
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 3
	db 60	; Waits for 1 line.

	db 3
	db 61, 127	; Waits for 128 lines.


Subsong0_Track12
	db 160
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 32
	db 60	; Waits for 1 line.

	db 25
	db 60	; Waits for 1 line.

	db 32
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 32
	db 60	; Waits for 1 line.

	db 25
	db 60	; Waits for 1 line.

	db 32
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 32
	db 60	; Waits for 1 line.

	db 25
	db 60	; Waits for 1 line.

	db 32
	db 60	; Waits for 1 line.

	db 25
	db 60	; Waits for 1 line.

	db 32
	db 60	; Waits for 1 line.

	db 25
	db 60	; Waits for 1 line.

	db 31
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 41
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 41
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 46
	db 60	; Waits for 1 line.

	db 48
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 31
	db 60	; Waits for 1 line.

	db 24
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 24
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 24
	db 61, 127	; Waits for 128 lines.


Subsong0_Track13
	db 129
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 1
	db 60	; Waits for 1 line.

	db 1
	db 60	; Waits for 1 line.

	db 1
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 1
	db 60	; Waits for 1 line.

	db 1
	db 60	; Waits for 1 line.

	db 1
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 1
	db 60	; Waits for 1 line.

	db 1
	db 60	; Waits for 1 line.

	db 1
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 1
	db 60	; Waits for 1 line.

	db 1
	db 60	; Waits for 1 line.

	db 0
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 0
	db 60	; Waits for 1 line.

	db 0
	db 60	; Waits for 1 line.

	db 0
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 0
	db 60	; Waits for 1 line.

	db 0
	db 60	; Waits for 1 line.

	db 0
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 0
	db 60	; Waits for 1 line.

	db 0
	db 60	; Waits for 1 line.

	db 0
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 0
	db 60	; Waits for 1 line.

	db 0
	db 61, 127	; Waits for 128 lines.


Subsong0_Track14
	db 145
	db 1	; New Instrument (1).
	db 61, 6	; Waits for 7 lines.

	db 12
	db 61, 10	; Waits for 11 lines.

	db 17
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 17
	db 60	; Waits for 1 line.

	db 19
	db 60	; Waits for 1 line.

	db 21
	db 60	; Waits for 1 line.

	db 22
	db 60	; Waits for 1 line.

	db 24
	db 61, 18	; Waits for 19 lines.

	db 24
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 24
	db 60	; Waits for 1 line.

	db 25
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 27
	db 61, 127	; Waits for 128 lines.


Subsong0_Track15
	db 173
	db 1	; New Instrument (1).
	db 61, 6	; Waits for 7 lines.

	db 45
	db 60	; Waits for 1 line.

	db 45
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 43
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 45
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 45
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 46
	db 60	; Waits for 1 line.

	db 48
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 51
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 53
	db 60	; Waits for 1 line.

	db 53
	db 60	; Waits for 1 line.

	db 55
	db 60	; Waits for 1 line.

	db 63
	db 74	; Escape note (74).
	db 60	; Waits for 1 line.

	db 63
	db 75	; Escape note (75).
	db 60	; Waits for 1 line.

	db 63
	db 77	; Escape note (77).
	db 61, 6	; Waits for 7 lines.

	db 51
	db 60	; Waits for 1 line.

	db 53
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 55
	db 61, 127	; Waits for 128 lines.


Subsong0_Track16
	db 157
	db 1	; New Instrument (1).
	db 61, 19	; Waits for 20 lines.

	db 29
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 29
	db 60	; Waits for 1 line.

	db 27
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 25
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 27
	db 62 + 2 * 64	; Optimized wait for 4 lines.

	db 25
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 24
	db 61, 14	; Waits for 15 lines.

	db 24
	db 61, 127	; Waits for 128 lines.


Subsong0_Track17
	db 177
	db 1	; New Instrument (1).
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 49
	db 60	; Waits for 1 line.

	db 49
	db 60	; Waits for 1 line.

	db 51
	db 60	; Waits for 1 line.

	db 53
	db 60	; Waits for 1 line.

	db 55
	db 60	; Waits for 1 line.

	db 63
	db 73	; Escape note (73).
	db 62 + 2 * 64	; Optimized wait for 4 lines.

	db 63
	db 73	; Escape note (73).
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 63
	db 73	; Escape note (73).
	db 60	; Waits for 1 line.

	db 55
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 53
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 63
	db 73	; Escape note (73).
	db 62 + 2 * 64	; Optimized wait for 4 lines.

	db 53
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 51
	db 60	; Waits for 1 line.

	db 51
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 49
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 51
	db 62 + 2 * 64	; Optimized wait for 4 lines.

	db 51
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 51
	db 60	; Waits for 1 line.

	db 49
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 51
	db 61, 127	; Waits for 128 lines.


Subsong0_Track18
	db 141
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 13
	db 60	; Waits for 1 line.

	db 13
	db 60	; Waits for 1 line.

	db 13
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 13
	db 60	; Waits for 1 line.

	db 13
	db 60	; Waits for 1 line.

	db 13
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 13
	db 60	; Waits for 1 line.

	db 13
	db 60	; Waits for 1 line.

	db 13
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 13
	db 60	; Waits for 1 line.

	db 13
	db 60	; Waits for 1 line.

	db 20
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 20
	db 60	; Waits for 1 line.

	db 20
	db 60	; Waits for 1 line.

	db 20
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 20
	db 60	; Waits for 1 line.

	db 20
	db 60	; Waits for 1 line.

	db 20
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 20
	db 60	; Waits for 1 line.

	db 20
	db 60	; Waits for 1 line.

	db 20
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 20
	db 60	; Waits for 1 line.

	db 20
	db 61, 127	; Waits for 128 lines.


Subsong0_Track19
	db 150
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 22
	db 60	; Waits for 1 line.

	db 24
	db 60	; Waits for 1 line.

	db 25
	db 61, 14	; Waits for 15 lines.

	db 24
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 22
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 20
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 20
	db 60	; Waits for 1 line.

	db 22
	db 60	; Waits for 1 line.

	db 24
	db 61, 14	; Waits for 15 lines.

	db 22
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 20
	db 61, 127	; Waits for 128 lines.


Subsong0_Track20
	db 177
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 49
	db 60	; Waits for 1 line.

	db 48
	db 60	; Waits for 1 line.

	db 49
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 49
	db 60	; Waits for 1 line.

	db 51
	db 60	; Waits for 1 line.

	db 53
	db 61, 6	; Waits for 7 lines.

	db 51
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 49
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 48
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 48
	db 60	; Waits for 1 line.

	db 46
	db 60	; Waits for 1 line.

	db 48
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 48
	db 60	; Waits for 1 line.

	db 49
	db 60	; Waits for 1 line.

	db 51
	db 61, 6	; Waits for 7 lines.

	db 49
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 48
	db 61, 127	; Waits for 128 lines.


Subsong0_Track21
	db 134
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 6
	db 60	; Waits for 1 line.

	db 6
	db 60	; Waits for 1 line.

	db 6
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 6
	db 60	; Waits for 1 line.

	db 6
	db 60	; Waits for 1 line.

	db 6
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 6
	db 60	; Waits for 1 line.

	db 6
	db 60	; Waits for 1 line.

	db 6
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 6
	db 60	; Waits for 1 line.

	db 6
	db 60	; Waits for 1 line.

	db 5
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 5
	db 60	; Waits for 1 line.

	db 5
	db 60	; Waits for 1 line.

	db 5
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 5
	db 60	; Waits for 1 line.

	db 5
	db 60	; Waits for 1 line.

	db 5
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 5
	db 60	; Waits for 1 line.

	db 5
	db 60	; Waits for 1 line.

	db 5
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 5
	db 60	; Waits for 1 line.

	db 5
	db 61, 127	; Waits for 128 lines.


Subsong0_Track22
	db 147
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 19
	db 60	; Waits for 1 line.

	db 21
	db 60	; Waits for 1 line.

	db 23
	db 61, 14	; Waits for 15 lines.

	db 26
	db 61, 6	; Waits for 7 lines.

	db 24
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 12
	db 60	; Waits for 1 line.

	db 12
	db 60	; Waits for 1 line.

	db 12
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 12
	db 60	; Waits for 1 line.

	db 12
	db 60	; Waits for 1 line.

	db 12
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 12
	db 60	; Waits for 1 line.

	db 12
	db 60	; Waits for 1 line.

	db 12
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 12
	db 61, 127	; Waits for 128 lines.


Subsong0_Track23
	db 175
	db 1	; New Instrument (1).
	db 61, 6	; Waits for 7 lines.

	db 47
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 47
	db 60	; Waits for 1 line.

	db 48
	db 60	; Waits for 1 line.

	db 50
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 50
	db 60	; Waits for 1 line.

	db 52
	db 60	; Waits for 1 line.

	db 53
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 55
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 40
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 40
	db 60	; Waits for 1 line.

	db 40
	db 60	; Waits for 1 line.

	db 39
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 39
	db 60	; Waits for 1 line.

	db 39
	db 60	; Waits for 1 line.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 38
	db 60	; Waits for 1 line.

	db 38
	db 60	; Waits for 1 line.

	db 37
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 37
	db 61, 127	; Waits for 128 lines.


Subsong0_Track24
	db 135
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 7
	db 60	; Waits for 1 line.

	db 7
	db 60	; Waits for 1 line.

	db 7
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 7
	db 60	; Waits for 1 line.

	db 7
	db 60	; Waits for 1 line.

	db 7
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 7
	db 60	; Waits for 1 line.

	db 7
	db 60	; Waits for 1 line.

	db 7
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 7
	db 60	; Waits for 1 line.

	db 7
	db 60	; Waits for 1 line.

	db 12
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 0
	db 60	; Waits for 1 line.

	db 0
	db 60	; Waits for 1 line.

	db 0
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 0
	db 60	; Waits for 1 line.

	db 0
	db 60	; Waits for 1 line.

	db 0
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 0
	db 60	; Waits for 1 line.

	db 0
	db 60	; Waits for 1 line.

	db 0
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 2
	db 60	; Waits for 1 line.

	db 4
	db 61, 127	; Waits for 128 lines.


Subsong0_Track25
	db 157
	db 1	; New Instrument (1).
	db 61, 22	; Waits for 23 lines.

	db 32
	db 61, 6	; Waits for 7 lines.

	db 31
	db 61, 6	; Waits for 7 lines.

	db 28
	db 61, 14	; Waits for 15 lines.

	db 24
	db 61, 127	; Waits for 128 lines.


Subsong0_Track26
	db 191
	db 73	; Escape note (73).
	db 1	; New Instrument (1).
	db 61, 22	; Waits for 23 lines.

	db 63
	db 76	; Escape note (76).
	db 61, 6	; Waits for 7 lines.

	db 63
	db 75	; Escape note (75).
	db 61, 6	; Waits for 7 lines.

	db 55
	db 61, 14	; Waits for 15 lines.

	db 52
	db 61, 127	; Waits for 128 lines.


Subsong0_Track27
	db 153
	db 1	; New Instrument (1).
	db 61, 22	; Waits for 23 lines.

	db 29
	db 61, 6	; Waits for 7 lines.

	db 28
	db 61, 6	; Waits for 7 lines.

	db 24
	db 61, 14	; Waits for 15 lines.

	db 24
	db 61, 127	; Waits for 128 lines.


Subsong0_Track28
	db 151
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 29
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 32
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 35
	db 60	; Waits for 1 line.

	db 41
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 44
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 47
	db 61, 14	; Waits for 15 lines.

	db 48
	db 61, 6	; Waits for 7 lines.

	db 36
	db 60	; Waits for 1 line.

	db 36
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 36
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 36
	db 61, 127	; Waits for 128 lines.


Subsong0_Track29
	db 139
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 11
	db 60	; Waits for 1 line.

	db 11
	db 60	; Waits for 1 line.

	db 11
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 11
	db 60	; Waits for 1 line.

	db 11
	db 60	; Waits for 1 line.

	db 11
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 11
	db 60	; Waits for 1 line.

	db 11
	db 60	; Waits for 1 line.

	db 11
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 11
	db 60	; Waits for 1 line.

	db 11
	db 60	; Waits for 1 line.

	db 12
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 12
	db 60	; Waits for 1 line.

	db 12
	db 60	; Waits for 1 line.

	db 12
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 12
	db 60	; Waits for 1 line.

	db 12
	db 60	; Waits for 1 line.

	db 12
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 12
	db 60	; Waits for 1 line.

	db 12
	db 60	; Waits for 1 line.

	db 12
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 12
	db 60	; Waits for 1 line.

	db 12
	db 61, 127	; Waits for 128 lines.


Subsong0_Track30
	db 153
	db 1	; New Instrument (1).
	db 61, 22	; Waits for 23 lines.

	db 29
	db 61, 6	; Waits for 7 lines.

	db 28
	db 61, 6	; Waits for 7 lines.

	db 24
	db 61, 14	; Waits for 15 lines.

	db 21
	db 61, 127	; Waits for 128 lines.


Subsong0_Track31
	db 150
	db 1	; New Instrument (1).
	db 61, 22	; Waits for 23 lines.

	db 25
	db 61, 6	; Waits for 7 lines.

	db 24
	db 61, 6	; Waits for 7 lines.

	db 20
	db 61, 14	; Waits for 15 lines.

	db 17
	db 61, 127	; Waits for 128 lines.


Subsong0_Track32
	db 177
	db 1	; New Instrument (1).
	db 61, 22	; Waits for 23 lines.

	db 54
	db 61, 6	; Waits for 7 lines.

	db 53
	db 61, 6	; Waits for 7 lines.

	db 48
	db 61, 14	; Waits for 15 lines.

	db 44
	db 61, 127	; Waits for 128 lines.


; The speed tracks
Subsong0_SpeedTrack0
	db 6	; Value: 3.
	db 253	; Wait for 127 lines.
Subsong0_SpeedTrack1
	db 255	; Wait for 128 lines.

; The event tracks
Subsong0_EventTrack0
	db 255	; Wait for 128 lines.

Subsong0_DisarkByteRegionEnd0
; Subsong 1
; ----------------------
Subsong1_DisarkByteRegionStart0
Subsong1_Start
	db 2	; ReplayFrequency (0=12.5hz, 1=25, 2=50, 3=100, 4=150, 5=300).
	db 0	; Digichannel (0-2).
	db 1	; PSG count (>0).
	db 0	; Loop start index (>=0).
	db 3	; End index (>=0).
	db 6	; Initial speed (>=0).
	db 17	; Base note index (>=0).

Subsong1_Linker
Subsong1_DisarkPointerRegionStart1
; Position 0
Subsong1_Linker_Loop
	dw Subsong1_Track0
	dw Subsong1_Track1
	dw Subsong1_Track2
	dw Subsong1_LinkerBlock0

; Position 1
	dw Subsong1_Track3
	dw Subsong1_Track4
	dw Subsong1_Track5
	dw Subsong1_LinkerBlock0

; Position 2
	dw Subsong1_Track6
	dw Subsong1_Track7
	dw Subsong1_Track8
	dw Subsong1_LinkerBlock0

; Position 3
	dw Subsong1_Track9
	dw Subsong1_Track10
	dw Subsong1_Track11
	dw Subsong1_LinkerBlock1

Subsong1_DisarkPointerRegionEnd1
	dw 0	; Loop.
Subsong1_DisarkWordForceReference2
	dw Subsong1_Linker_Loop

Subsong1_LinkerBlock0
	db 64	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
Subsong1_DisarkWordForceReference3
	dw Subsong1_SpeedTrack0	; SpeedTrack address.
Subsong1_DisarkWordForceReference4
	dw Subsong1_EventTrack0	; EventTrack address.
Subsong1_LinkerBlock1
	db 40	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
Subsong1_DisarkWordForceReference5
	dw Subsong1_SpeedTrack0	; SpeedTrack address.
Subsong1_DisarkWordForceReference6
	dw Subsong1_EventTrack0	; EventTrack address.

Subsong1_Track0
	db 230
	db 1	; New Instrument (1).
	db 0	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 45
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 45
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 45
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 45
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 37
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 45
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 37
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 45
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 37
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 45
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 37
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 45
	db 61, 127	; Waits for 128 lines.


Subsong1_Track1
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 233
	db 1	; New Instrument (1).
	db 0	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 46
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 41
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 46
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 41
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 46
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 41
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 46
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 40
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 46
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 40
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 46
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 40
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 46
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 40
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 46
	db 61, 127	; Waits for 128 lines.


Subsong1_Track2
	db 218
	db 1	; New Instrument (1).
	db 0	; Index to an effect block.
	db 61, 14	; Waits for 15 lines.

	db 29
	db 61, 6	; Waits for 7 lines.

	db 33
	db 61, 6	; Waits for 7 lines.

	db 32
	db 61, 6	; Waits for 7 lines.

	db 25
	db 61, 127	; Waits for 128 lines.


Subsong1_Track3
	db 164
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 45
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 36
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 45
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 36
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 45
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 36
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 45
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 35
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 45
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 35
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 45
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 35
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 45
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 35
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 45
	db 61, 127	; Waits for 128 lines.


Subsong1_Track4
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 167
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 46
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 39
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 46
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 39
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 46
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 39
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 46
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 46
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 46
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 46
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 46
	db 61, 127	; Waits for 128 lines.


Subsong1_Track5
	db 152
	db 1	; New Instrument (1).
	db 61, 20	; Waits for 21 lines.

	db 27
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 32
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 31
	db 61, 6	; Waits for 7 lines.

	db 23
	db 61, 127	; Waits for 128 lines.


Subsong1_Track6
	db 162
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 34
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 34
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 34
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 33
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 33
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 33
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 33
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 61, 127	; Waits for 128 lines.


Subsong1_Track7
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 166
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 45
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 45
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 45
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 45
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 45
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 45
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 45
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 45
	db 61, 127	; Waits for 128 lines.


Subsong1_Track8
	db 150
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 21
	db 60	; Waits for 1 line.

	db 22
	db 61, 10	; Waits for 11 lines.

	db 26
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 34
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 33
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 21
	db 60	; Waits for 1 line.

	db 20
	db 60	; Waits for 1 line.

	db 21
	db 61, 10	; Waits for 11 lines.

	db 26
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 33
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 32
	db 61, 127	; Waits for 128 lines.


Subsong1_Track9
	db 159
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 40
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 37
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 40
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 46
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 46
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 46
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 52
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 52
	db 61, 127	; Waits for 128 lines.


Subsong1_Track10
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 165
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 40
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 46
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 49
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 49
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 49
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 55
	db 61, 127	; Waits for 128 lines.


Subsong1_Track11
	db 149
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 25
	db 60	; Waits for 1 line.

	db 28
	db 60	; Waits for 1 line.

	db 25
	db 60	; Waits for 1 line.

	db 28
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 28
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 34
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 34
	db 60	; Waits for 1 line.

	db 37
	db 60	; Waits for 1 line.

	db 40
	db 60	; Waits for 1 line.

	db 37
	db 60	; Waits for 1 line.

	db 34
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 34
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 28
	db 60	; Waits for 1 line.

	db 25
	db 61, 127	; Waits for 128 lines.


; The speed tracks
Subsong1_SpeedTrack0
	db 8	; Value: 4.
	db 253	; Wait for 127 lines.

; The event tracks
Subsong1_EventTrack0
	db 255	; Wait for 128 lines.

Subsong1_DisarkByteRegionEnd0
; Subsong 2
; ----------------------
Subsong2_DisarkByteRegionStart0
Subsong2_Start
	db 2	; ReplayFrequency (0=12.5hz, 1=25, 2=50, 3=100, 4=150, 5=300).
	db 0	; Digichannel (0-2).
	db 1	; PSG count (>0).
	db 0	; Loop start index (>=0).
	db 0	; End index (>=0).
	db 6	; Initial speed (>=0).
	db 22	; Base note index (>=0).

Subsong2_Linker
Subsong2_DisarkPointerRegionStart1
; Position 0
Subsong2_Linker_Loop
	dw Subsong2_Track0
	dw Subsong2_Track1
	dw Subsong2_Track2
	dw Subsong2_LinkerBlock0

Subsong2_DisarkPointerRegionEnd1
	dw 0	; Loop.
Subsong2_DisarkWordForceReference2
	dw Subsong2_Linker_Loop

Subsong2_LinkerBlock0
	db 64	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
Subsong2_DisarkWordForceReference3
	dw Subsong2_SpeedTrack0	; SpeedTrack address.
Subsong2_DisarkWordForceReference4
	dw Subsong2_EventTrack0	; EventTrack address.

Subsong2_Track0
	db 60	; Waits for 1 line.

	db 241
	db 1	; New Instrument (1).
	db 0	; Index to an effect block.
	db 61, 8	; Waits for 9 lines.

	db 50
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 52
	db 60	; Waits for 1 line.

	db 55
	db 61, 6	; Waits for 7 lines.

	db 54
	db 60	; Waits for 1 line.

	db 55
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 54
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 52
	db 61, 8	; Waits for 9 lines.

	db 49
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 45
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 49
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 50
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 54
	db 60	; Waits for 1 line.

	db 52
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 50
	db 61, 127	; Waits for 128 lines.


Subsong2_Track1
	db 60	; Waits for 1 line.

	db 225
	db 1	; New Instrument (1).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 37
	db 60	; Waits for 1 line.

	db 40
	db 60	; Waits for 1 line.

	db 33
	db 60	; Waits for 1 line.

	db 37
	db 60	; Waits for 1 line.

	db 40
	db 60	; Waits for 1 line.

	db 33
	db 60	; Waits for 1 line.

	db 37
	db 60	; Waits for 1 line.

	db 35
	db 60	; Waits for 1 line.

	db 38
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 35
	db 60	; Waits for 1 line.

	db 38
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 35
	db 60	; Waits for 1 line.

	db 38
	db 60	; Waits for 1 line.

	db 33
	db 60	; Waits for 1 line.

	db 37
	db 60	; Waits for 1 line.

	db 40
	db 60	; Waits for 1 line.

	db 33
	db 60	; Waits for 1 line.

	db 37
	db 60	; Waits for 1 line.

	db 40
	db 60	; Waits for 1 line.

	db 33
	db 60	; Waits for 1 line.

	db 37
	db 60	; Waits for 1 line.

	db 35
	db 60	; Waits for 1 line.

	db 38
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 35
	db 60	; Waits for 1 line.

	db 38
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 35
	db 60	; Waits for 1 line.

	db 38
	db 61, 127	; Waits for 128 lines.


Subsong2_Track2
	db 60	; Waits for 1 line.

	db 225
	db 1	; New Instrument (1).
	db 0	; Index to an effect block.
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 28
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 33
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 31
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 26
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 31
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 33
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 28
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 33
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 31
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 26
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 31
	db 61, 127	; Waits for 128 lines.


; The speed tracks
Subsong2_SpeedTrack0
	db 1	; Wait for 1 lines.
	db 12	; Value: 6.
	db 251	; Wait for 126 lines.

; The event tracks
Subsong2_EventTrack0
	db 255	; Wait for 128 lines.

Subsong2_DisarkByteRegionEnd0
; Subsong 3
; ----------------------
Subsong3_DisarkByteRegionStart0
Subsong3_Start
	db 2	; ReplayFrequency (0=12.5hz, 1=25, 2=50, 3=100, 4=150, 5=300).
	db 0	; Digichannel (0-2).
	db 1	; PSG count (>0).
	db 0	; Loop start index (>=0).
	db 2	; End index (>=0).
	db 6	; Initial speed (>=0).
	db 31	; Base note index (>=0).

Subsong3_Linker
Subsong3_DisarkPointerRegionStart1
; Position 0
Subsong3_Linker_Loop
	dw Subsong3_Track0
	dw Subsong3_Track1
	dw Subsong3_Track2
	dw Subsong3_LinkerBlock0

; Position 1
	dw Subsong3_Track3
	dw Subsong3_Track4
	dw Subsong3_Track5
	dw Subsong3_LinkerBlock1

; Position 2
	dw Subsong3_Track6
	dw Subsong3_Track6
	dw Subsong3_Track6
	dw Subsong3_LinkerBlock2

Subsong3_DisarkPointerRegionEnd1
	dw 0	; Loop.
Subsong3_DisarkWordForceReference2
	dw Subsong3_Linker_Loop

Subsong3_LinkerBlock0
	db 64	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
Subsong3_DisarkWordForceReference3
	dw Subsong3_SpeedTrack0	; SpeedTrack address.
Subsong3_DisarkWordForceReference4
	dw Subsong3_EventTrack0	; EventTrack address.
Subsong3_LinkerBlock1
	db 21	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
Subsong3_DisarkWordForceReference5
	dw Subsong3_SpeedTrack0	; SpeedTrack address.
Subsong3_DisarkWordForceReference6
	dw Subsong3_EventTrack0	; EventTrack address.
Subsong3_LinkerBlock2
	db 5	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
Subsong3_DisarkWordForceReference7
	dw Subsong3_SpeedTrack0	; SpeedTrack address.
Subsong3_DisarkWordForceReference8
	dw Subsong3_EventTrack0	; EventTrack address.

Subsong3_Track0
	db 228
	db 1	; New Instrument (1).
	db 0	; Index to an effect block.
	db 61, 10	; Waits for 11 lines.

	db 36
	db 38
	db 40
	db 41
	db 43
	db 61, 10	; Waits for 11 lines.

	db 43
	db 43
	db 43
	db 60	; Waits for 1 line.

	db 48
	db 61, 10	; Waits for 11 lines.

	db 48
	db 50
	db 52
	db 53
	db 55
	db 61, 10	; Waits for 11 lines.

	db 31
	db 31
	db 60	; Waits for 1 line.

	db 31
	db 61, 127	; Waits for 128 lines.


Subsong3_Track1
	db 62 + 2 * 64	; Optimized wait for 4 lines.

	db 211
	db 1	; New Instrument (1).
	db 0	; Index to an effect block.
	db 19
	db 19
	db 60	; Waits for 1 line.

	db 24
	db 61, 10	; Waits for 11 lines.

	db 24
	db 26
	db 28
	db 29
	db 31
	db 61, 10	; Waits for 11 lines.

	db 31
	db 31
	db 31
	db 60	; Waits for 1 line.

	db 36
	db 61, 10	; Waits for 11 lines.

	db 36
	db 38
	db 40
	db 41
	db 43
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 23
	db 23
	db 60	; Waits for 1 line.

	db 23
	db 61, 127	; Waits for 128 lines.


Subsong3_Track2
	db 216
	db 1	; New Instrument (1).
	db 0	; Index to an effect block.
	db 61, 14	; Waits for 15 lines.

	db 22
	db 61, 14	; Waits for 15 lines.

	db 20
	db 61, 14	; Waits for 15 lines.

	db 19
	db 61, 10	; Waits for 11 lines.

	db 19
	db 19
	db 60	; Waits for 1 line.

	db 19
	db 61, 127	; Waits for 128 lines.


Subsong3_Track3
	db 164
	db 1	; New Instrument (1).
	db 61, 127	; Waits for 128 lines.


Subsong3_Track4
	db 156
	db 1	; New Instrument (1).
	db 61, 127	; Waits for 128 lines.


Subsong3_Track5
	db 147
	db 1	; New Instrument (1).
	db 61, 127	; Waits for 128 lines.


Subsong3_Track6
	db 61, 127	; Waits for 128 lines.


; The speed tracks
Subsong3_SpeedTrack0
	db 255	; Wait for 128 lines.

; The event tracks
Subsong3_EventTrack0
	db 255	; Wait for 128 lines.

Subsong3_DisarkByteRegionEnd0
; Subsong 4
; ----------------------
Subsong4_DisarkByteRegionStart0
Subsong4_Start
	db 2	; ReplayFrequency (0=12.5hz, 1=25, 2=50, 3=100, 4=150, 5=300).
	db 0	; Digichannel (0-2).
	db 1	; PSG count (>0).
	db 0	; Loop start index (>=0).
	db 1	; End index (>=0).
	db 6	; Initial speed (>=0).
	db 17	; Base note index (>=0).

Subsong4_Linker
Subsong4_DisarkPointerRegionStart1
; Position 0
Subsong4_Linker_Loop
	dw Subsong4_Track0
	dw Subsong4_Track1
	dw Subsong4_Track2
	dw Subsong4_LinkerBlock0

; Position 1
	dw Subsong4_Track3
	dw Subsong4_Track3
	dw Subsong4_Track3
	dw Subsong4_LinkerBlock1

Subsong4_DisarkPointerRegionEnd1
	dw 0	; Loop.
Subsong4_DisarkWordForceReference2
	dw Subsong4_Linker_Loop

Subsong4_LinkerBlock0
	db 16	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
Subsong4_DisarkWordForceReference3
	dw Subsong4_SpeedTrack0	; SpeedTrack address.
Subsong4_DisarkWordForceReference4
	dw Subsong4_EventTrack0	; EventTrack address.
Subsong4_LinkerBlock1
	db 5	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
Subsong4_DisarkWordForceReference5
	dw Subsong4_SpeedTrack0	; SpeedTrack address.
Subsong4_DisarkWordForceReference6
	dw Subsong4_EventTrack0	; EventTrack address.

Subsong4_Track0
	db 60	; Waits for 1 line.

	db 244
	db 1	; New Instrument (1).
	db 1	; Index to an effect block.
	db 53
	db 54
	db 55
	db 61, 127	; Waits for 128 lines.


Subsong4_Track1
	db 60	; Waits for 1 line.

	db 235
	db 1	; New Instrument (1).
	db 1	; Index to an effect block.
	db 44
	db 45
	db 46
	db 61, 127	; Waits for 128 lines.


Subsong4_Track2
	db 60	; Waits for 1 line.

	db 232
	db 1	; New Instrument (1).
	db 1	; Index to an effect block.
	db 41
	db 42
	db 43
	db 61, 127	; Waits for 128 lines.


Subsong4_Track3
	db 61, 127	; Waits for 128 lines.


; The speed tracks
Subsong4_SpeedTrack0
	db 255	; Wait for 128 lines.

; The event tracks
Subsong4_EventTrack0
	db 255	; Wait for 128 lines.

Subsong4_DisarkByteRegionEnd0
; Subsong 5
; ----------------------
Subsong5_DisarkByteRegionStart0
Subsong5_Start
	db 2	; ReplayFrequency (0=12.5hz, 1=25, 2=50, 3=100, 4=150, 5=300).
	db 0	; Digichannel (0-2).
	db 1	; PSG count (>0).
	db 0	; Loop start index (>=0).
	db 1	; End index (>=0).
	db 6	; Initial speed (>=0).
	db 17	; Base note index (>=0).

Subsong5_Linker
Subsong5_DisarkPointerRegionStart1
; Position 0
Subsong5_Linker_Loop
	dw Subsong5_Track0
	dw Subsong5_Track1
	dw Subsong5_Track2
	dw Subsong5_LinkerBlock0

; Position 1
	dw Subsong5_Track3
	dw Subsong5_Track3
	dw Subsong5_Track3
	dw Subsong5_LinkerBlock1

Subsong5_DisarkPointerRegionEnd1
	dw 0	; Loop.
Subsong5_DisarkWordForceReference2
	dw Subsong5_Linker_Loop

Subsong5_LinkerBlock0
	db 32	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
Subsong5_DisarkWordForceReference3
	dw Subsong5_SpeedTrack0	; SpeedTrack address.
Subsong5_DisarkWordForceReference4
	dw Subsong5_EventTrack0	; EventTrack address.
Subsong5_LinkerBlock1
	db 5	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
Subsong5_DisarkWordForceReference5
	dw Subsong5_SpeedTrack0	; SpeedTrack address.
Subsong5_DisarkWordForceReference6
	dw Subsong5_EventTrack0	; EventTrack address.

Subsong5_Track0
	db 242
	db 1	; New Instrument (1).
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 49
	db 60	; Waits for 1 line.

	db 46
	db 60	; Waits for 1 line.

	db 40
	db 60	; Waits for 1 line.

	db 39
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 51
	db 60	; Waits for 1 line.

	db 55
	db 61, 127	; Waits for 128 lines.


Subsong5_Track1
	db 124	; No note, but effects.
	db 1	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


Subsong5_Track2
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 242
	db 1	; New Instrument (1).
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 49
	db 60	; Waits for 1 line.

	db 46
	db 60	; Waits for 1 line.

	db 40
	db 60	; Waits for 1 line.

	db 39
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 51
	db 60	; Waits for 1 line.

	db 55
	db 61, 127	; Waits for 128 lines.


Subsong5_Track3
	db 61, 127	; Waits for 128 lines.


; The speed tracks
Subsong5_SpeedTrack0
	db 8	; Value: 4.
	db 253	; Wait for 127 lines.

; The event tracks
Subsong5_EventTrack0
	db 255	; Wait for 128 lines.

Subsong5_DisarkByteRegionEnd0
; Subsong 6
; ----------------------
Subsong6_DisarkByteRegionStart0
Subsong6_Start
	db 2	; ReplayFrequency (0=12.5hz, 1=25, 2=50, 3=100, 4=150, 5=300).
	db 0	; Digichannel (0-2).
	db 1	; PSG count (>0).
	db 0	; Loop start index (>=0).
	db 4	; End index (>=0).
	db 6	; Initial speed (>=0).
	db 24	; Base note index (>=0).

Subsong6_Linker
Subsong6_DisarkPointerRegionStart1
; Position 0
Subsong6_Linker_Loop
	dw Subsong6_Track0
	dw Subsong6_Track1
	dw Subsong6_Track2
	dw Subsong6_LinkerBlock0

; Position 1
	dw Subsong6_Track3
	dw Subsong6_Track4
	dw Subsong6_Track5
	dw Subsong6_LinkerBlock0

; Position 2
	dw Subsong6_Track6
	dw Subsong6_Track4
	dw Subsong6_Track5
	dw Subsong6_LinkerBlock0

; Position 3
	dw Subsong6_Track7
	dw Subsong6_Track8
	dw Subsong6_Track9
	dw Subsong6_LinkerBlock0

; Position 4
	dw Subsong6_Track10
	dw Subsong6_Track11
	dw Subsong6_Track12
	dw Subsong6_LinkerBlock0

Subsong6_DisarkPointerRegionEnd1
	dw 0	; Loop.
Subsong6_DisarkWordForceReference2
	dw Subsong6_Linker_Loop

Subsong6_LinkerBlock0
	db 48	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
Subsong6_DisarkWordForceReference3
	dw Subsong6_SpeedTrack0	; SpeedTrack address.
Subsong6_DisarkWordForceReference4
	dw Subsong6_EventTrack0	; EventTrack address.

Subsong6_Track0
	db 61, 43	; Waits for 44 lines.

	db 233
	db 1	; New Instrument (1).
	db 0	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


Subsong6_Track1
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 221
	db 1	; New Instrument (1).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 34
	db 60	; Waits for 1 line.

	db 38
	db 60	; Waits for 1 line.

	db 34
	db 60	; Waits for 1 line.

	db 29
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 26
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 34
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 26
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 31
	db 60	; Waits for 1 line.

	db 34
	db 60	; Waits for 1 line.

	db 41
	db 60	; Waits for 1 line.

	db 34
	db 60	; Waits for 1 line.

	db 31
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 29
	db 60	; Waits for 1 line.

	db 36
	db 60	; Waits for 1 line.

	db 39
	db 60	; Waits for 1 line.

	db 36
	db 60	; Waits for 1 line.

	db 29
	db 61, 127	; Waits for 128 lines.


Subsong6_Track2
	db 214
	db 1	; New Instrument (1).
	db 0	; Index to an effect block.
	db 61, 10	; Waits for 11 lines.

	db 19
	db 61, 10	; Waits for 11 lines.

	db 24
	db 61, 10	; Waits for 11 lines.

	db 17
	db 61, 127	; Waits for 128 lines.


Subsong6_Track3
	db 174
	db 1	; New Instrument (1).
	db 61, 6	; Waits for 7 lines.

	db 41
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 50
	db 61, 6	; Waits for 7 lines.

	db 46
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 53
	db 61, 18	; Waits for 19 lines.

	db 41
	db 61, 127	; Waits for 128 lines.


Subsong6_Track4
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 157
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 34
	db 60	; Waits for 1 line.

	db 38
	db 60	; Waits for 1 line.

	db 34
	db 60	; Waits for 1 line.

	db 29
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 26
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 34
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 26
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 31
	db 60	; Waits for 1 line.

	db 34
	db 60	; Waits for 1 line.

	db 41
	db 60	; Waits for 1 line.

	db 34
	db 60	; Waits for 1 line.

	db 31
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 29
	db 60	; Waits for 1 line.

	db 36
	db 60	; Waits for 1 line.

	db 39
	db 60	; Waits for 1 line.

	db 36
	db 60	; Waits for 1 line.

	db 29
	db 61, 127	; Waits for 128 lines.


Subsong6_Track5
	db 150
	db 1	; New Instrument (1).
	db 61, 10	; Waits for 11 lines.

	db 19
	db 61, 10	; Waits for 11 lines.

	db 24
	db 61, 10	; Waits for 11 lines.

	db 17
	db 61, 127	; Waits for 128 lines.


Subsong6_Track6
	db 174
	db 1	; New Instrument (1).
	db 61, 6	; Waits for 7 lines.

	db 41
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 50
	db 61, 6	; Waits for 7 lines.

	db 46
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 53
	db 61, 18	; Waits for 19 lines.

	db 53
	db 61, 127	; Waits for 128 lines.


Subsong6_Track7
	db 183
	db 1	; New Instrument (1).
	db 61, 10	; Waits for 11 lines.

	db 45
	db 61, 6	; Waits for 7 lines.

	db 55
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 53
	db 61, 10	; Waits for 11 lines.

	db 50
	db 61, 127	; Waits for 128 lines.


Subsong6_Track8
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 159
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 34
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 34
	db 60	; Waits for 1 line.

	db 31
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 29
	db 60	; Waits for 1 line.

	db 33
	db 60	; Waits for 1 line.

	db 29
	db 60	; Waits for 1 line.

	db 33
	db 60	; Waits for 1 line.

	db 29
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 29
	db 60	; Waits for 1 line.

	db 34
	db 60	; Waits for 1 line.

	db 29
	db 60	; Waits for 1 line.

	db 34
	db 60	; Waits for 1 line.

	db 29
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 26
	db 60	; Waits for 1 line.

	db 34
	db 60	; Waits for 1 line.

	db 26
	db 60	; Waits for 1 line.

	db 34
	db 60	; Waits for 1 line.

	db 26
	db 61, 127	; Waits for 128 lines.


Subsong6_Track9
	db 143
	db 1	; New Instrument (1).
	db 61, 10	; Waits for 11 lines.

	db 17
	db 61, 10	; Waits for 11 lines.

	db 22
	db 61, 10	; Waits for 11 lines.

	db 19
	db 61, 127	; Waits for 128 lines.


Subsong6_Track10
	db 178
	db 1	; New Instrument (1).
	db 61, 10	; Waits for 11 lines.

	db 50
	db 61, 6	; Waits for 7 lines.

	db 48
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 46
	db 61, 18	; Waits for 19 lines.

	db 41
	db 61, 127	; Waits for 128 lines.


Subsong6_Track11
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 159
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 34
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 34
	db 60	; Waits for 1 line.

	db 31
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 24
	db 60	; Waits for 1 line.

	db 33
	db 60	; Waits for 1 line.

	db 24
	db 60	; Waits for 1 line.

	db 33
	db 60	; Waits for 1 line.

	db 24
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 29
	db 60	; Waits for 1 line.

	db 34
	db 60	; Waits for 1 line.

	db 29
	db 60	; Waits for 1 line.

	db 34
	db 60	; Waits for 1 line.

	db 29
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 29
	db 60	; Waits for 1 line.

	db 34
	db 60	; Waits for 1 line.

	db 29
	db 60	; Waits for 1 line.

	db 34
	db 60	; Waits for 1 line.

	db 29
	db 61, 127	; Waits for 128 lines.


Subsong6_Track12
	db 152
	db 1	; New Instrument (1).
	db 61, 10	; Waits for 11 lines.

	db 17
	db 61, 10	; Waits for 11 lines.

	db 22
	db 61, 10	; Waits for 11 lines.

	db 22
	db 61, 127	; Waits for 128 lines.


; The speed tracks
Subsong6_SpeedTrack0
	db 255	; Wait for 128 lines.

; The event tracks
Subsong6_EventTrack0
	db 255	; Wait for 128 lines.

Subsong6_DisarkByteRegionEnd0
; Subsong 7
; ----------------------
Subsong7_DisarkByteRegionStart0
Subsong7_Start
	db 2	; ReplayFrequency (0=12.5hz, 1=25, 2=50, 3=100, 4=150, 5=300).
	db 0	; Digichannel (0-2).
	db 1	; PSG count (>0).
	db 0	; Loop start index (>=0).
	db 0	; End index (>=0).
	db 6	; Initial speed (>=0).
	db 21	; Base note index (>=0).

Subsong7_Linker
Subsong7_DisarkPointerRegionStart1
; Position 0
Subsong7_Linker_Loop
	dw Subsong7_Track0
	dw Subsong7_Track1
	dw Subsong7_Track0
	dw Subsong7_LinkerBlock0

Subsong7_DisarkPointerRegionEnd1
	dw 0	; Loop.
Subsong7_DisarkWordForceReference2
	dw Subsong7_Linker_Loop

Subsong7_LinkerBlock0
	db 53	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
Subsong7_DisarkWordForceReference3
	dw Subsong7_SpeedTrack0	; SpeedTrack address.
Subsong7_DisarkWordForceReference4
	dw Subsong7_EventTrack0	; EventTrack address.

Subsong7_Track0
	db 61, 127	; Waits for 128 lines.


Subsong7_Track1
	db 235
	db 1	; New Instrument (1).
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 48
	db 60	; Waits for 1 line.

	db 50
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 60	; Waits for 1 line.

	db 48
	db 60	; Waits for 1 line.

	db 50
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 60	; Waits for 1 line.

	db 48
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 55
	db 60	; Waits for 1 line.

	db 53
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 50
	db 60	; Waits for 1 line.

	db 51
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 46
	db 60	; Waits for 1 line.

	db 43
	db 61, 127	; Waits for 128 lines.


; The speed tracks
Subsong7_SpeedTrack0
	db 255	; Wait for 128 lines.

; The event tracks
Subsong7_EventTrack0
	db 255	; Wait for 128 lines.

Subsong7_DisarkByteRegionEnd0
