ORG #A000
DEFM "The Panties of Zelda"
DEFM "   v2.7.1 (beta)    "
DEFM "    30-10-2020      "
DEFM "                    "
DEFM "                    "
DEFM "                    "
DEFM "                    "
DEFM "                    "
DEFM "                    "
DEFM "(fire 2) to hold the"
DEFM "scenario.           "
DEFM "                    "
DEFM "(fire 1) to zap the "
DEFM "scenario.           "
DEFM "                    "
DEFM "                    "
DEFM "                    "
DEFM "                    "
DEFM "                    "
DEFM "                    "
DEFM "                    "
DEFM "A Long time ago in a"
DEFM "so far  world, lived"
DEFM "a beautiful princess"
DEFM "named ZELDA.        "
DEFM "                    "
DEFM "                    "
DEFM "                    "
DEFM "                    "
DEFM "                    "
DEFM "                    "
DEFM "                    "
DEFM "She reigned over the"
DEFM "kindom of Hyrule and"
DEFM "had  perverted  its "
DEFM "people into lust and"
DEFM "sins.               "
DEFM "                    "
DEFM "                    "
DEFM "                    "
DEFM "                    "
DEFM "                    "
DEFM "                    "
DEFM "                    "
DEFM "                    "
DEFM "But one  shinny day,"
DEFM "Gods   decided   to "
DEFM "punish her for forc-"
DEFM "ing  the  Elevs  to "
DEFM "matte   with   the  "
DEFM "otters to the nearby"
DEFM "village.            "
DEFM "                    "
DEFM "                    "
DEFM "Zelda was exiled to "
DEFM "the  other  side  of"
DEFM "the ocean, isolated "
DEFM "and above all ...   "
DEFM "without any spare   "
DEFM "panties!!!          "
DEFM "                    "
DEFM "                    "
DEFM "                    "
DEFM "                    "
DEFM "                    "
DEFM "Meanwhile ...       "
DEFM "                    "
DEFM "                    "
DEFM "                    "
DEFM "                    "
DEFM "... on a very close "
DEFM "planet ...          "
DEFM "                    "
DEFM "                    "
DEFM "                    "
DEFM "                    "
DEFM "A  plumber  made  a "
DEFM "giant telescope that"
DEFM "allowed him to see  "
DEFM "the princess's bush."
DEFM "                    "
DEFM "                    "
DEFM "                    "
DEFM "                    "
DEFM "                    "
DEFM "                    "
DEFM "Unable to hold back,"
DEFM "Mario made the trip,"
DEFM "taking  his  biggest"
DEFM "own pipe !          "
DEFM "                    "
DEFM "                    "
DEFM "                    "
DEFM "                    "
DEFM "                    "
DEFM "Link, an agent from "
DEFM "Fistendo Inc., got  "
DEFM "missioned  to  find "
DEFM "the  4 panties that "
DEFM "Zelda left into the "
DEFM "4 donjons of Hyrule."
DEFM "                    "
DEFM "                    "
DEFM "--------------------"
DEFM "                    "
DEFM "                    "
DEFM "                    "
DEFM "--------------------"
DEFM "                    "
DEFM "                    "
DEFM "--------------------"
DEFM "                    "
DEFM "                    "
DEFM "Zik : Arkos Tracker2"
DEFM "                    "
DEFM "                    "
DEFM "                    "
DEFM "Beta test WinAPE:   "
DEFM "- JB LE DARON       "
DEFM "- XYPHOE            "
DEFM "- SHORYU            "
DEFM "                    "
DEFM "Beta test CPC+      "
DEFM "- AST               "
DEFM "                    "
DEFM "                    "
DEFM "                    "
DEFM "Thanks :            "
DEFM "Roudoudou, AST, Gol-"
DEFM "em13, La brigade des"
DEFM "nops, Siko and all  "
DEFM "of those who helped "
DEFM "me during my streams"
DEFM "                    "
DEFM "                    "
DEFM "                    "
DEFM " ***   *   *  ****  "
DEFM "*   *  **  *  *   * "  
DEFM "*****  * * *  *   * " 
DEFM "*   *  *  **  *   * "
DEFM "*   *  *   *  ****  "
DEFM "                    "
DEFM "                    "
DEFM "Special  thank  to  "
DEFM "BDCIRON for his ASM "
DEFM "lessons, or this    "
DEFM "game  would  never  "
DEFM "been relased ;)     "
DEFM "                    "
DEFM "                    "
DEFM "                    "
DEFM "       AND !!!      "
DEFM "                    "
DEFM "                    "
DEFM "happy birthday to   "
DEFM "the AMSTRAD CPC6128+"
DEFM "witch gets its 30   "
DEFM "year old this year !"
DEFM "                    "
DEFM "                    "
DEFM "                    "
DEFM "                    "
DEFM "                    "
DEFM "                    "
DEFM "                    "
DEFM "                    "
DEFM "                    "
DEFM "                    "
DEFM "                    "
DEFM "                    "
DEFM "                    "
DEFM "                    "
DEFM "                    "
DEFM "$                   "



