ORG #A000
DEFM "La Culotte de Zelda "
DEFM "        v3.0        "
DEFM "     24-12-2020     "
DEFM "                    "
DEFM "                    "
DEFM "                    "
DEFM "                    "
DEFM "                    "
DEFM "                    "
DEFM "Il  y  a  longtemps,"
DEFM "dans  un monde  fort"
DEFM "lointain, vivait une"
DEFM "princesse  du nom de"
DEFM "Zelda.              "
DEFM "                    "
DEFM "                    "
DEFM "                    "
DEFM "                    "
DEFM "                    "
DEFM "                    "
DEFM "Elle reignait sur le"
DEFM "royaume  d'Hyrule et"
DEFM "avait  perverti  ses"
DEFM "habitants  dans  la "
DEFM "luxure et le vice.  "
DEFM "                    "
DEFM "                    "
DEFM "                    "
DEFM "                    "
DEFM "                    "
DEFM "                    "
DEFM "Mais  un beau  jour,"
DEFM "les Dieux d_ciderent"
DEFM "de  la punir  pour  "
DEFM "avoir  oblig_  les  "
DEFM "Elfes  @  se  repro-"
DEFM "duire  avec  les co-"
DEFM "cottes  du  village "
DEFM "d'@  cot_.          "
DEFM "                    "
DEFM "                    "
DEFM "                    "
DEFM "                    "
DEFM "                    "
DEFM "                    "
DEFM "Zelda fut exil_e  de"
DEFM "l'autre  cot_   de  "
DEFM "l'oc_an, isol_e  et "
DEFM "surtout, sans aucune"
DEFM "culotte!            "
DEFM "                    "
DEFM "                    "
DEFM "                    "
DEFM "                    "
DEFM "                    "
DEFM "                    "
DEFM "                    "
DEFM "                    "
DEFM "Pendant ce temps ..."
DEFM "                    "
DEFM "                    "
DEFM "                    "
DEFM "                    "
DEFM "... sur  une planete"
DEFM "tres tres proche ..."
DEFM "                    "
DEFM "                    "
DEFM "                    "
DEFM "                    "
DEFM "Un  plombier  avait "
DEFM "fabriqu_  un  grand "
DEFM "t_lescope  g_ant qui"
DEFM "lui  permettait  de "
DEFM "voir  ....          "
DEFM "                    "
DEFM "... la touffe  de la"
DEFM " princesse Zelda !!!"
DEFM "                    "
DEFM "                    "
DEFM "Ne pouvant plus  se "
DEFM "retenir, Mario  fit "
DEFM "le voyage, emmenant "
DEFM "avec  lui  son  plus"
DEFM "gros tuyau !        "
DEFM "                    "
DEFM "                    "
DEFM "Link,  un espion de "
DEFM "l'agence  Fistendo, "
DEFM "fut  missionn_  pour"
DEFM "retrouver les 4 cul-"
DEFM "ottes  que  Zelda a "
DEFM "laiss_ trainer  dans"
DEFM "les  4  donjons  du "
DEFM "royaume d'Hyrule ..."
DEFM "                    "
DEFM "                    "
DEFM "--------------------"
DEFM "                    "
DEFM "                    "
DEFM "--------------------"
DEFM "                    "
DEFM "                    "
DEFM "--------------------"
DEFM "                    "
DEFM "                    "
DEFM "Zik : Arkos Tracker2"
DEFM "                    "
DEFM "                    "
DEFM "                    "
DEFM "Beta test WinAPE:   "
DEFM "- JB LE DARON       "
DEFM "- XYPHOE            "
DEFM "- SHORYU            "
DEFM "                    "
DEFM "Beta test CPC+      "
DEFM "- AST               "
DEFM "                    "
DEFM "Remerciements @ :   "
DEFM "                    "
DEFM "Richard Wilson  pour"
DEFM "son super emulateur!"
DEFM "Roudoudou pour  son "
DEFM "assembleur RASM qui "
DEFM "est  mega cool ! Et "
DEFM "aussi @ AST, Golem13"
DEFM "Siko, La brigade des"
DEFM "nops, et puis @ tout"
DEFM "ceux qui m'ont enc.."
DEFM "ourag_s pendant mes "
DEFM "stream chiants ! ;) "
DEFM "                    "
DEFM "                    "
DEFM "   *****    ******  "
DEFM "   *          **    "
DEFM "   ***        **    " 
DEFM "   *          **    "
DEFM "   *****      **    "
DEFM "                    "
DEFM "Tres  GROS  merci  @"
DEFM "BDCIRON  pour  ses  "
DEFM "cours  d'ASM  sans  "
DEFM "lesquels  ce  jeu   "
DEFM "n'aurait  jamais  pu"
DEFM "voir le jour ;)     "
DEFM "                    "
DEFM "       ET !!!       "
DEFM "                    "
DEFM "Joyeux anniversaire "
DEFM "@ l'AMSTRAD CPC6128+"
DEFM "qui fete ses 30ans  "
DEFM "cette ann_e 2020 !!!"
DEFM "                    "
DEFM "                    "
DEFM "$                   "



